spring:
  application:
    name: springPractice
  datasource:
    url: jdbc:h2:tcp://localhost/~/springPractice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true